### ISSUE TITLE
Hackintosh on HP 8470P

### ISSUE THREAD

**Issue by justinqian42** [afzl-wtu/afzl-wtu.github.io#1]
Hi Muhammad,

I got your message via github. Somehow your comment in the original post was removed. [#73](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/issues/73)

So your 8470P's brightness issue is fixed up?

Regards,
Justin

**Comment by afzl-wtu** [comment]
> Hi Muhammad,
> 
> I got your message via github. Somehow your comment in the original post was removed. [#73](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC/issues/73)
> 
> So your 8470P's brightness issue is fixed up?
> 
> Regards, Justin

Sorry I see it today, Github never notified about issue on my own repos. Yeah I had fixed the issue a long time ago
